package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Test Yandex market")
    void generatedTest() {
        step("open https://market.yandex.ru/", () -> {
            step("// todo: just add selenium action");
        });

        step("add items to cart", () -> {
            step("// todo: just add selenium action");
        });

        step("go to the cart to make sure that there are added goods", () -> {
            step("// todo: just add selenium action");
        });

        step("empty shopping cart", () -> {
            step("// todo: just add selenium action");
        });

        step("check cart is empty", () -> {
            step("// todo: just add selenium action");
        });

        step("Go to home page", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://market.yandex.ru/'", () ->
            open("https://market.yandex.ru/"));

        step("Page title should have text 'Интернет-магазин Яндекс.Маркет — покупки с быстрой доставкой'", () -> {
            String expectedTitle = "Интернет-магазин Яндекс.Маркет — покупки с быстрой доставкой";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://market.yandex.ru/'", () ->
            open("https://market.yandex.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}